theme = "pepew" # tokyonight_storm with highlighted primary selection

[editor]
  color-modes = true
  true-color  = true
  mouse       = true
  line-number = "relative"
  bufferline  = "multiple"
  end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
  cursor-line = "warning"

[editor.lsp]
  display-inlay-hints = true

[editor.soft-wrap]
  enable = true

[editor.cursor-shape]
  insert = "bar"
  normal = "block"
  select = "underline"

[editor.file-picker]
  hidden = false

[editor.statusline]
  left = ["mode", "spinner"]
  center = ["file-name"]
  right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
  separator = "|"
  # mode.normal = "NORMAL"
  # mode.insert = "INSERT"
  # mode.select = "SELECT"
  diagnostics = ["warning", "error"]
  workspace-diagnostics = ["warning", "error"]

[editor.indent-guides]
  render = true
  character = "¦"
  skip-levels = 1

[keys.normal]
  C-left = "jump_view_left"
  C-right = "jump_view_right"
  C-up = "jump_view_up"
  C-down = "jump_view_down"
  A-z = "rotate_selection_contents_backward"
  A-v = "rotate_selection_contents_forward"
  A-l = "repeat_last_motion"
  A-r = "flip_selections"
  A-t = "ensure_selections_forward"
  "}" = "goto_next_paragraph"
  "{" = "goto_prev_paragraph"
  "X" = "select_line_above"

[keys.insert]
  C-right = "move_next_word_start"
  C-left  = "move_prev_word_end"

[keys.select]
  "}" = "goto_next_paragraph"
  "{" = "goto_prev_paragraph"
  "X" = "select_line_above"

[keys.normal.g]
  "," = "goto_line_end"
[keys.select.g]
  "," = "goto_line_end"
  
[keys.normal.m.n]
  q = "@f'lmi'" # select next inside single-quotes
  d = '@f"lmi"' # select next inside double-quotes

[keys.normal.m.n.a]
  q = "@f'lma'" # select next around single-quotes
  d = '@f"lma"' # select next around double-quotes
