theme = "pepew"

[editor]
  color-modes = true
  true-color  = true
  line-number = "relative"
  mouse       = true
  bufferline  = "multiple"
  end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
  cursor-line = "warning"

[editor.lsp]
  display-inlay-hints = true

[editor.soft-wrap]
  enable = true

[editor.cursor-shape]
  insert = "bar"
  normal = "block"
  select = "underline"

[editor.file-picker]
  hidden = false

[editor.statusline]
  left = ["mode", "spinner"]
  center = ["file-name"]
  right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
  separator = "│"
  # mode.normal = "NORMAL"
  # mode.insert = "INSERT"
  # mode.select = "SELECT"
  diagnostics = ["warning", "error"]
  workspace-diagnostics = ["warning", "error"]

[editor.indent-guides]
  render = true
  character = "┊" # Some characters that work well: "▏", "╎", "┆", "┊", "⸽"
  skip-levels = 1

[keys.normal]
  C-left  = "jump_view_left"
  C-right = "jump_view_right"
  C-up    = "jump_view_up"
  C-down  = "jump_view_down"
  "{"     = "goto_prev_paragraph"
  "}"     = "goto_next_paragraph"

[keys.select]
  "{" = "goto_prev_paragraph"
  "}" = "goto_next_paragraph"

[keys.normal.g]
  "," = "goto_line_end"

[keys.select.g]
  "," = "goto_line_end"

[keys.normal.m.n]
  d = '@f"lmi"'
  q = "@f'lmi'" 
  # t = "@t>mi>"

[keys.normal.m.n.a]
  q = "@f'lma'" 
  d = '@f"lma"'
