# Set the prefix to ctrl-n
set -g prefix C-s

# Remove the old prefix
unbind C-b

# Send Ctrl-s to applications by pressing it twice
bind C-s send-prefix

# Add some colors
set -g status-bg cyan # status bar background color
set -g window-status-style bg=yellow # inactive window
set -g window-status-current-style bg=red,fg=white # active window

# Enable Mouse
set -g mouse
